site_name: FSAA Documentation

plugins: 
  - mkdocstrings

nav:
  - FSAA: index.md
  - Initializers: initializers.md
  - Updaters: updaters.md
  - Losses: losses.md
  - Masks: masks.md
  - Transforms: transforms.md
  - Models: models.md

theme:
  name: "material"